<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-03-31 01:21:30                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ProtoGuest extends AutoProtoGuest {/*_*/}
?>