<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-06-08 19:31:25                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoGuestDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'guest';
		}
		
		public function getObjectName()
		{
			return 'Guest';
		}
		
		public function getSequence()
		{
			return 'guest_id';
		}
		
		public function getLinkName()
		{
			return 'invitation';
		}
	}
?>