<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-03-31 01:21:30                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class GuestDAO extends AutoGuestDAO
	{
		public function getByKey($key)
		{
			$guest =
				Criteria::create($this)->
					add(
						Expression::orBlock(
							Expression::eq('secretKey', $key),
							Expression::eq('openKey', $key)
						)
					)->
					get();

			if ($guest)
				$guest->setKey($key);

			return $guest;
		}
	}
?>