<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-03-31 21:40:38                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoGuest extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Guest', 4, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
				'displayName' => LightMetaProperty::fill(new LightMetaProperty(), 'displayName', 'display_name', 'string', null, 255, true, true, false, null, null),
				'fileName' => LightMetaProperty::fill(new LightMetaProperty(), 'fileName', 'file_name', 'string', null, 255, true, true, false, null, null),
				'result' => LightMetaProperty::fill(new LightMetaProperty(), 'result', 'result_id', 'enumeration', 'Result', null, true, false, false, 1, null),
				'quantity' => LightMetaProperty::fill(new LightMetaProperty(), 'quantity', 'quantity_id', 'enumeration', 'Quantity', null, true, false, false, 1, null),
				'secretKey' => LightMetaProperty::fill(new LightMetaProperty(), 'secretKey', 'secret_key', 'string', null, 40, true, true, false, null, null),
				'openKey' => LightMetaProperty::fill(new LightMetaProperty(), 'openKey', 'open_key', 'string', null, 40, true, true, false, null, null),
				'optionalText' => LightMetaProperty::fill(new LightMetaProperty(), 'optionalText', 'optional_text', 'string', null, 100, false, true, false, null, null),
				'optionalResult' => LightMetaProperty::fill(new LightMetaProperty(), 'optionalResult', 'optional_result_id', 'enumeration', 'Result', null, true, false, false, 1, null),
				'comment' => LightMetaProperty::fill(new LightMetaProperty(), 'comment', null, 'string', null, null, false, true, false, null, null)
			);
		}
	}
?>