<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-03-31 21:40:38                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoGuest extends NamedObject
	{
		protected $displayName = null;
		protected $fileName = null;
		protected $result = null;
		protected $quantity = null;
		protected $secretKey = null;
		protected $openKey = null;
		protected $optionalText = null;
		protected $optionalResult = null;
		protected $comment = null;
		
		public function getDisplayName()
		{
			return $this->displayName;
		}
		
		/**
		 * @return Guest
		**/
		public function setDisplayName($displayName)
		{
			$this->displayName = $displayName;
			
			return $this;
		}
		
		public function getFileName()
		{
			return $this->fileName;
		}
		
		/**
		 * @return Guest
		**/
		public function setFileName($fileName)
		{
			$this->fileName = $fileName;
			
			return $this;
		}
		
		/**
		 * @return Result
		**/
		public function getResult()
		{
			return $this->result;
		}
		
		/**
		 * @return Guest
		**/
		public function setResult(Result $result)
		{
			$this->result = $result;
			
			return $this;
		}
		
		/**
		 * @return Guest
		**/
		public function dropResult()
		{
			$this->result = null;
			
			return $this;
		}
		
		/**
		 * @return Quantity
		**/
		public function getQuantity()
		{
			return $this->quantity;
		}
		
		/**
		 * @return Guest
		**/
		public function setQuantity(Quantity $quantity)
		{
			$this->quantity = $quantity;
			
			return $this;
		}
		
		/**
		 * @return Guest
		**/
		public function dropQuantity()
		{
			$this->quantity = null;
			
			return $this;
		}
		
		public function getSecretKey()
		{
			return $this->secretKey;
		}
		
		/**
		 * @return Guest
		**/
		public function setSecretKey($secretKey)
		{
			$this->secretKey = $secretKey;
			
			return $this;
		}
		
		public function getOpenKey()
		{
			return $this->openKey;
		}
		
		/**
		 * @return Guest
		**/
		public function setOpenKey($openKey)
		{
			$this->openKey = $openKey;
			
			return $this;
		}
		
		public function getOptionalText()
		{
			return $this->optionalText;
		}
		
		/**
		 * @return Guest
		**/
		public function setOptionalText($optionalText)
		{
			$this->optionalText = $optionalText;
			
			return $this;
		}
		
		/**
		 * @return Result
		**/
		public function getOptionalResult()
		{
			return $this->optionalResult;
		}
		
		/**
		 * @return Guest
		**/
		public function setOptionalResult(Result $optionalResult)
		{
			$this->optionalResult = $optionalResult;
			
			return $this;
		}
		
		/**
		 * @return Guest
		**/
		public function dropOptionalResult()
		{
			$this->optionalResult = null;
			
			return $this;
		}
		
		public function getComment()
		{
			return $this->comment;
		}
		
		/**
		 * @return Guest
		**/
		public function setComment($comment)
		{
			$this->comment = $comment;
			
			return $this;
		}
	}
?>