<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-03-31 01:21:30                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class Guest extends AutoGuest implements Prototyped, DAOConnected
	{
		private $key		= null;
		private $anonyous	= false;

		/**
		 * @return Guest
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return GuestDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('GuestDAO');
		}
		
		/**
		 * @return ProtoGuest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoGuest');
		}
		
		/**
		 * @return Guest
		 */
		public static function no()
		{
			return
				Guest::create()->
					setDisplayName('Приглашение')->
					setQuantity(Quantity::singular())->
					setKey('noGuest')->
					setAnonyous();
		}
		
		public function getKey()
		{
			return $this->key;
		}

		/**
		 * @return Guest
		 */
		public function setKey($key)
		{
			$this->key = $key;

			return $this;
		}

		public function isSecretKey()
		{
			return $this->key == $this->getSecretKey();
		}
		
		/**
		 * @return Guest 
		 */
		public function setAnonyous($anonyous = true)
		{
			$this->anonyous = $anonyous;
			
			return $this;
		}

		public function isAnonyous() 
		{
			return $this->anonyous === true;
		}

	}
?>