<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2011-03-31 01:21:30                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class Quantity extends Enumeration
	{
		const SINGULAR_ID	= 1;
		const PLURAL_ID		= 2;

		protected $names = array(
			self::SINGULAR_ID	=> 'Один человек',
			self::PLURAL_ID		=> 'Пара человек'
		);

		protected $plans = array(
			self::SINGULAR_ID	=> 'планируешь',
			self::PLURAL_ID		=> 'планируете'
		);

		protected $willGo = array(
			self::SINGULAR_ID	=> 'Я приду',
			self::PLURAL_ID		=> 'Мы придем'
		);

		protected $stayHome = array(
			self::SINGULAR_ID	=> 'Я не приду',
			self::PLURAL_ID		=> 'Мы не придем'
		);

		/**
		 * @return Quantity
		 */
		public static function create($id)
		{
			return new self($id);
		}

		/**
		 * @return Quantity
		 */
		public static function singular()
		{
			return new self(self::SINGULAR_ID);
		}

		/**
		 * @return Quantity
		 */
		public static function plural()
		{
			return new self(self::PLURAL_ID);
		}

		public function getPlans()
		{
			return $this->plans[$this->id];
		}

		public function getWillGo()
		{
			return $this->willGo[$this->id];
		}

		public function getStayHome()
		{
			return $this->stayHome[$this->id];
		}
	}
?>